/*
 * generated by Xtext
 */
package org.palladiosimulator.commons.stoex.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.palladiosimulator.commons.stoex.ui.internal.StoExActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StoExExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return StoExActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return StoExActivator.getInstance().getInjector(StoExActivator.ORG_PALLADIOSIMULATOR_COMMONS_STOEX_STOEX);
	}
	
}
