/*
 * generated by Xtext
 */
package org.palladiosimulator.commons.stoex.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StoExUiModule extends org.palladiosimulator.commons.stoex.ui.AbstractStoExUiModule {
	public StoExUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
