/*
 * generated by Xtext
 */
package org.palladiosimulator.commons.stoex.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.palladiosimulator.commons.stoex.services.StoExGrammarAccess;

public class StoExParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private StoExGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.palladiosimulator.commons.stoex.parser.antlr.internal.InternalStoExParser createParser(XtextTokenStream stream) {
		return new org.palladiosimulator.commons.stoex.parser.antlr.internal.InternalStoExParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "expression";
	}
	
	public StoExGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(StoExGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
