/*
 * generated by Xtext
 */
package org.palladiosimulator.commons.stoex;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StoExRuntimeModule extends org.palladiosimulator.commons.stoex.AbstractStoExRuntimeModule {

}
