/*
* generated by Xtext
*/
package org.palladiosimulator.commons.stoex;

import org.palladiosimulator.commons.stoex.StoExStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class StoExStandaloneSetup extends StoExStandaloneSetupGenerated{

	public static void doSetup() {
		new StoExStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

